import type { MenuCategory, MenuItem } from "@/types";

export const mockCategories: MenuCategory[] = [
  {
    id: "cat_001",
    restaurantId: "rest_001",
    name: "BBQ & Grill",
    slug: "bbq-grill",
    description: "Freshly grilled tikkas, seekh kababs, and boti",
    icon: "🔥",
    sortOrder: 1,
    isActive: true,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2022-01-15T00:00:00Z",
  },
  {
    id: "cat_002",
    restaurantId: "rest_001",
    name: "Karahi & Handi",
    slug: "karahi-handi",
    description: "Slow-cooked karahis and handis bursting with flavor",
    icon: "🍲",
    sortOrder: 2,
    isActive: true,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2022-01-15T00:00:00Z",
  },
  {
    id: "cat_003",
    restaurantId: "rest_001",
    name: "Biryani & Rice",
    slug: "biryani-rice",
    description: "Aromatic biryanis and rice dishes",
    icon: "🍚",
    sortOrder: 3,
    isActive: true,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2022-01-15T00:00:00Z",
  },
  {
    id: "cat_004",
    restaurantId: "rest_001",
    name: "Burgers & Wraps",
    slug: "burgers-wraps",
    description: "Loaded burgers and crispy wraps",
    icon: "🍔",
    sortOrder: 4,
    isActive: true,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2022-01-15T00:00:00Z",
  },
  {
    id: "cat_005",
    restaurantId: "rest_001",
    name: "Breads",
    slug: "breads",
    description: "Naans, rotis, and parathas from the tandoor",
    icon: "🫓",
    sortOrder: 5,
    isActive: true,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2022-01-15T00:00:00Z",
  },
  {
    id: "cat_006",
    restaurantId: "rest_001",
    name: "Desserts",
    slug: "desserts",
    description: "Traditional mithai and modern desserts",
    icon: "🍮",
    sortOrder: 6,
    isActive: true,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2022-01-15T00:00:00Z",
  },
  {
    id: "cat_007",
    restaurantId: "rest_001",
    name: "Drinks",
    slug: "drinks",
    description: "Fresh juices, lassi, and cold drinks",
    icon: "🥤",
    sortOrder: 7,
    isActive: true,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2022-01-15T00:00:00Z",
  },
  {
    id: "cat_008",
    restaurantId: "rest_001",
    name: "Starters",
    slug: "starters",
    description: "Soups, salads, and small plates",
    icon: "🥗",
    sortOrder: 8,
    isActive: true,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2022-01-15T00:00:00Z",
  },
];

export const mockMenuItems: MenuItem[] = [
  // BBQ & Grill
  {
    id: "item_001",
    restaurantId: "rest_001",
    categoryId: "cat_001",
    name: "Chicken Tikka",
    slug: "chicken-tikka",
    description: "Tender chicken marinated in spiced yogurt and grilled to perfection in our clay tandoor",
    image: "/images/menu/chicken-tikka.jpg",
    basePrice: 750,
    variants: [
      { id: "var_001a", name: "Half (6 pcs)", price: 750, isDefault: true, isAvailable: true },
      { id: "var_001b", name: "Full (12 pcs)", price: 1400, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [
      {
        id: "mod_001",
        name: "Extra Sauces",
        isRequired: false,
        minSelections: 0,
        maxSelections: 3,
        options: [
          { id: "opt_001a", name: "Mint Chutney", priceAdjustment: 0, isDefault: true, isAvailable: true },
          { id: "opt_001b", name: "Tamarind Sauce", priceAdjustment: 0, isDefault: false, isAvailable: true },
          { id: "opt_001c", name: "Garlic Mayo", priceAdjustment: 50, isDefault: false, isAvailable: true },
        ],
      },
    ],
    dietaryTags: ["halal"],
    spiceLevel: "medium",
    preparationTimeMinutes: 20,
    calories: 320,
    status: "available",
    isFeatured: true,
    isPopular: true,
    sortOrder: 1,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "item_002",
    restaurantId: "rest_001",
    categoryId: "cat_001",
    name: "Seekh Kabab",
    slug: "seekh-kabab",
    description: "Minced beef mixed with aromatic spices, shaped on skewers and char-grilled",
    image: "/images/menu/seekh-kabab.jpg",
    basePrice: 850,
    variants: [
      { id: "var_002a", name: "4 pieces", price: 850, isDefault: true, isAvailable: true },
      { id: "var_002b", name: "8 pieces", price: 1600, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [],
    dietaryTags: ["halal"],
    spiceLevel: "hot",
    preparationTimeMinutes: 18,
    calories: 280,
    status: "available",
    isFeatured: false,
    isPopular: true,
    sortOrder: 2,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "item_003",
    restaurantId: "rest_001",
    categoryId: "cat_001",
    name: "Boti Kabab",
    slug: "boti-kabab",
    description: "Juicy mutton pieces marinated overnight and grilled on open flame",
    image: "/images/menu/boti-kabab.jpg",
    basePrice: 1100,
    variants: [
      { id: "var_003a", name: "Half portion", price: 1100, isDefault: true, isAvailable: true },
      { id: "var_003b", name: "Full portion", price: 2000, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [],
    dietaryTags: ["halal"],
    spiceLevel: "medium",
    preparationTimeMinutes: 25,
    status: "available",
    isFeatured: true,
    isPopular: false,
    sortOrder: 3,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // Karahi & Handi
  {
    id: "item_004",
    restaurantId: "rest_001",
    categoryId: "cat_002",
    name: "Chicken Karahi",
    slug: "chicken-karahi",
    description: "Classic Lahori chicken karahi cooked in fresh tomatoes, green chillies and ginger",
    image: "/images/menu/chicken-karahi.jpg",
    basePrice: 1200,
    variants: [
      { id: "var_004a", name: "Half kg", price: 1200, isDefault: true, isAvailable: true },
      { id: "var_004b", name: "1 kg", price: 2200, isDefault: false, isAvailable: true },
      { id: "var_004c", name: "1.5 kg", price: 3100, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [
      {
        id: "mod_004",
        name: "Oil Preference",
        isRequired: false,
        minSelections: 0,
        maxSelections: 1,
        options: [
          { id: "opt_004a", name: "Normal Oil", priceAdjustment: 0, isDefault: true, isAvailable: true },
          { id: "opt_004b", name: "Less Oil", priceAdjustment: 0, isDefault: false, isAvailable: true },
          { id: "opt_004c", name: "Desi Ghee", priceAdjustment: 200, isDefault: false, isAvailable: true },
        ],
      },
    ],
    dietaryTags: ["halal"],
    spiceLevel: "hot",
    preparationTimeMinutes: 30,
    calories: 450,
    status: "available",
    isFeatured: true,
    isPopular: true,
    sortOrder: 1,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "item_005",
    restaurantId: "rest_001",
    categoryId: "cat_002",
    name: "Mutton Karahi",
    slug: "mutton-karahi",
    description: "Tender mutton slow-cooked in our signature karahi masala",
    image: "/images/menu/mutton-karahi.jpg",
    basePrice: 2200,
    variants: [
      { id: "var_005a", name: "Half kg", price: 2200, isDefault: true, isAvailable: true },
      { id: "var_005b", name: "1 kg", price: 4000, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [],
    dietaryTags: ["halal"],
    spiceLevel: "hot",
    preparationTimeMinutes: 45,
    status: "available",
    isFeatured: false,
    isPopular: true,
    sortOrder: 2,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // Biryani & Rice
  {
    id: "item_006",
    restaurantId: "rest_001",
    categoryId: "cat_003",
    name: "Chicken Biryani",
    slug: "chicken-biryani",
    description: "Fragrant basmati rice layered with spiced chicken, saffron and fried onions",
    image: "/images/menu/chicken-biryani.jpg",
    basePrice: 550,
    variants: [
      { id: "var_006a", name: "Single", price: 550, isDefault: true, isAvailable: true },
      { id: "var_006b", name: "Family (4 pax)", price: 1900, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [
      {
        id: "mod_006",
        name: "Extras",
        isRequired: false,
        minSelections: 0,
        maxSelections: 2,
        options: [
          { id: "opt_006a", name: "Raita", priceAdjustment: 80, isDefault: false, isAvailable: true },
          { id: "opt_006b", name: "Salad", priceAdjustment: 100, isDefault: false, isAvailable: true },
        ],
      },
    ],
    dietaryTags: ["halal"],
    spiceLevel: "medium",
    preparationTimeMinutes: 20,
    calories: 650,
    status: "available",
    isFeatured: true,
    isPopular: true,
    sortOrder: 1,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "item_007",
    restaurantId: "rest_001",
    categoryId: "cat_003",
    name: "Mutton Biryani",
    slug: "mutton-biryani",
    description: "Royal mutton biryani with whole spices and slow-cooked tender mutton",
    image: "/images/menu/mutton-biryani.jpg",
    basePrice: 750,
    variants: [
      { id: "var_007a", name: "Single", price: 750, isDefault: true, isAvailable: true },
      { id: "var_007b", name: "Family (4 pax)", price: 2600, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [],
    dietaryTags: ["halal"],
    spiceLevel: "medium",
    preparationTimeMinutes: 20,
    status: "available",
    isFeatured: false,
    isPopular: true,
    sortOrder: 2,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // Burgers
  {
    id: "item_008",
    restaurantId: "rest_001",
    categoryId: "cat_004",
    name: "Zaiqa Special Burger",
    slug: "zaiqa-special-burger",
    description: "Double beef patty, cheddar cheese, crispy lettuce, tomato and our secret sauce",
    image: "/images/menu/zaiqa-burger.jpg",
    basePrice: 650,
    variants: [
      { id: "var_008a", name: "Single", price: 650, isDefault: true, isAvailable: true },
      { id: "var_008b", name: "Double", price: 950, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [
      {
        id: "mod_008",
        name: "Add-ons",
        isRequired: false,
        minSelections: 0,
        maxSelections: 4,
        options: [
          { id: "opt_008a", name: "Extra Patty", priceAdjustment: 200, isDefault: false, isAvailable: true },
          { id: "opt_008b", name: "Extra Cheese", priceAdjustment: 80, isDefault: false, isAvailable: true },
          { id: "opt_008c", name: "Jalapenos", priceAdjustment: 50, isDefault: false, isAvailable: true },
          { id: "opt_008d", name: "Fried Egg", priceAdjustment: 80, isDefault: false, isAvailable: true },
        ],
      },
    ],
    dietaryTags: ["halal"],
    spiceLevel: "mild",
    preparationTimeMinutes: 12,
    calories: 780,
    status: "available",
    isFeatured: true,
    isPopular: true,
    sortOrder: 1,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // Breads
  {
    id: "item_009",
    restaurantId: "rest_001",
    categoryId: "cat_005",
    name: "Tandoori Naan",
    slug: "tandoori-naan",
    description: "Freshly baked leavened bread from our clay tandoor",
    basePrice: 60,
    variants: [],
    modifierGroups: [],
    dietaryTags: ["vegetarian"],
    spiceLevel: "none",
    preparationTimeMinutes: 5,
    calories: 180,
    status: "available",
    isFeatured: false,
    isPopular: true,
    sortOrder: 1,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "item_010",
    restaurantId: "rest_001",
    categoryId: "cat_005",
    name: "Butter Naan",
    slug: "butter-naan",
    description: "Tandoori naan brushed generously with fresh butter",
    basePrice: 80,
    variants: [],
    modifierGroups: [],
    dietaryTags: ["vegetarian"],
    spiceLevel: "none",
    preparationTimeMinutes: 5,
    calories: 220,
    status: "available",
    isFeatured: false,
    isPopular: true,
    sortOrder: 2,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // Desserts
  {
    id: "item_011",
    restaurantId: "rest_001",
    categoryId: "cat_006",
    name: "Gulab Jamun",
    slug: "gulab-jamun",
    description: "Soft milk-solid dumplings soaked in rose-flavored sugar syrup",
    basePrice: 180,
    variants: [
      { id: "var_011a", name: "2 pieces", price: 180, isDefault: true, isAvailable: true },
      { id: "var_011b", name: "4 pieces", price: 320, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [],
    dietaryTags: ["vegetarian"],
    spiceLevel: "none",
    preparationTimeMinutes: 5,
    calories: 380,
    status: "available",
    isFeatured: false,
    isPopular: true,
    sortOrder: 1,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "item_012",
    restaurantId: "rest_001",
    categoryId: "cat_006",
    name: "Kheer",
    slug: "kheer",
    description: "Creamy rice pudding slow-cooked with cardamom, pistachios and almonds",
    basePrice: 220,
    variants: [],
    modifierGroups: [],
    dietaryTags: ["vegetarian"],
    spiceLevel: "none",
    preparationTimeMinutes: 5,
    calories: 420,
    status: "available",
    isFeatured: false,
    isPopular: false,
    sortOrder: 2,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // Drinks
  {
    id: "item_013",
    restaurantId: "rest_001",
    categoryId: "cat_007",
    name: "Mango Lassi",
    slug: "mango-lassi",
    description: "Thick yogurt blended with fresh Chaunsa mango pulp and a hint of cardamom",
    basePrice: 250,
    variants: [
      { id: "var_013a", name: "Regular", price: 250, isDefault: true, isAvailable: true },
      { id: "var_013b", name: "Large", price: 380, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [],
    dietaryTags: ["vegetarian"],
    spiceLevel: "none",
    preparationTimeMinutes: 5,
    calories: 280,
    status: "available",
    isFeatured: false,
    isPopular: true,
    sortOrder: 1,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "item_014",
    restaurantId: "rest_001",
    categoryId: "cat_007",
    name: "Fresh Lime Soda",
    slug: "fresh-lime-soda",
    description: "Zesty fresh lime squeezed over chilled sparkling water with a pinch of salt",
    basePrice: 150,
    variants: [
      { id: "var_014a", name: "Sweet", price: 150, isDefault: true, isAvailable: true },
      { id: "var_014b", name: "Salted", price: 150, isDefault: false, isAvailable: true },
      { id: "var_014c", name: "Mixed", price: 150, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [],
    dietaryTags: ["vegetarian", "vegan"],
    spiceLevel: "none",
    preparationTimeMinutes: 3,
    calories: 80,
    status: "available",
    isFeatured: false,
    isPopular: true,
    sortOrder: 2,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // Starters
  {
    id: "item_015",
    restaurantId: "rest_001",
    categoryId: "cat_008",
    name: "Chicken Corn Soup",
    slug: "chicken-corn-soup",
    description: "Warm and hearty soup with shredded chicken, sweet corn and a drizzle of chilli vinegar",
    basePrice: 280,
    variants: [
      { id: "var_015a", name: "Regular", price: 280, isDefault: true, isAvailable: true },
      { id: "var_015b", name: "Large", price: 420, isDefault: false, isAvailable: true },
    ],
    modifierGroups: [],
    dietaryTags: ["halal"],
    spiceLevel: "mild",
    preparationTimeMinutes: 10,
    calories: 180,
    status: "available",
    isFeatured: false,
    isPopular: false,
    sortOrder: 1,
    createdAt: "2022-01-15T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];