import type { Order } from "@/types";

export const mockOrders: Order[] = [
  {
    id: "ord_001",
    orderNumber: "ORD-0041",
    restaurantId: "rest_001",
    branchId: "branch_001",
    tableId: "tbl_001",
    tableNumber: "T1",
    orderType: "dine_in",
    status: "confirmed",
    items: [
      {
        id: "oi_001",
        orderId: "ord_001",
        menuItemId: "item_001",
        menuItemName: "Chicken Tikka",
        categoryId: "cat_001",
        categoryName: "BBQ & Grill",
        quantity: 1,
        unitPrice: 750,
        selectedVariant: { variantId: "var_001a", variantName: "Half (6 pcs)", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 750,
        status: "pending",
        createdAt: "2024-11-30T19:15:00Z",
      },
      {
        id: "oi_002",
        orderId: "ord_001",
        menuItemId: "item_004",
        menuItemName: "Chicken Karahi",
        categoryId: "cat_002",
        categoryName: "Karahi & Handi",
        quantity: 1,
        unitPrice: 1200,
        selectedVariant: { variantId: "var_004a", variantName: "Half kg", priceAdjustment: 0 },
        selectedModifiers: [{ groupId: "mod_004", groupName: "Oil Preference", optionId: "opt_004c", optionName: "Desi Ghee", priceAdjustment: 200 }],
        itemTotal: 1400,
        status: "pending",
        createdAt: "2024-11-30T19:15:00Z",
      },
      {
        id: "oi_003",
        orderId: "ord_001",
        menuItemId: "item_009",
        menuItemName: "Tandoori Naan",
        categoryId: "cat_005",
        categoryName: "Breads",
        quantity: 3,
        unitPrice: 60,
        selectedModifiers: [],
        itemTotal: 180,
        status: "pending",
        createdAt: "2024-11-30T19:15:00Z",
      },
      {
        id: "oi_004",
        orderId: "ord_001",
        menuItemId: "item_013",
        menuItemName: "Mango Lassi",
        categoryId: "cat_007",
        categoryName: "Drinks",
        quantity: 2,
        unitPrice: 250,
        selectedVariant: { variantId: "var_013a", variantName: "Regular", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 500,
        status: "pending",
        createdAt: "2024-11-30T19:15:00Z",
      },
    ],
    subtotal: 2830,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 481,
    serviceChargeRate: 5,
    serviceChargeAmount: 142,
    deliveryFee: 0,
    total: 3453,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 3453,
    staffId: "staff_004",
    createdAt: "2024-11-30T19:15:00Z",
    updatedAt: "2024-11-30T19:22:00Z",
  },
  {
    id: "ord_002",
    orderNumber: "ORD-0040",
    restaurantId: "rest_001",
    branchId: "branch_001",
    tableId: "tbl_003",
    tableNumber: "T3",
    orderType: "dine_in",
    status: "confirmed",
    items: [
      {
        id: "oi_005",
        orderId: "ord_002",
        menuItemId: "item_006",
        menuItemName: "Chicken Biryani",
        categoryId: "cat_003",
        categoryName: "Biryani & Rice",
        quantity: 4,
        unitPrice: 550,
        selectedVariant: { variantId: "var_006a", variantName: "Single", priceAdjustment: 0 },
        selectedModifiers: [{ groupId: "mod_006", groupName: "Extras", optionId: "opt_006a", optionName: "Raita", priceAdjustment: 80 }],
        itemTotal: 2520,
        status: "pending",
        createdAt: "2024-11-30T18:00:00Z",
      },
      {
        id: "oi_006",
        orderId: "ord_002",
        menuItemId: "item_002",
        menuItemName: "Seekh Kabab",
        categoryId: "cat_001",
        categoryName: "BBQ & Grill",
        quantity: 1,
        unitPrice: 850,
        selectedVariant: { variantId: "var_002a", variantName: "4 pieces", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 850,
        status: "pending",
        createdAt: "2024-11-30T18:00:00Z",
      },
    ],
    subtotal: 3370,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 573,
    serviceChargeRate: 5,
    serviceChargeAmount: 169,
    deliveryFee: 0,
    total: 4112,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 4112,
    staffId: "staff_004",
    createdAt: "2024-11-30T18:00:00Z",
    updatedAt: "2024-11-30T19:00:00Z",
  },
  {
    id: "ord_003",
    orderNumber: "ORD-0039",
    restaurantId: "rest_001",
    branchId: "branch_001",
    tableId: "tbl_007",
    tableNumber: "T7",
    orderType: "dine_in",
    status: "confirmed",
    items: [
      {
        id: "oi_007",
        orderId: "ord_003",
        menuItemId: "item_005",
        menuItemName: "Mutton Karahi",
        categoryId: "cat_002",
        categoryName: "Karahi & Handi",
        quantity: 1,
        unitPrice: 2200,
        selectedVariant: { variantId: "var_005a", variantName: "Half kg", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 2200,
        status: "pending",
        createdAt: "2024-11-30T19:45:00Z",
      },
      {
        id: "oi_008",
        orderId: "ord_003",
        menuItemId: "item_010",
        menuItemName: "Butter Naan",
        categoryId: "cat_005",
        categoryName: "Breads",
        quantity: 4,
        unitPrice: 80,
        selectedModifiers: [],
        itemTotal: 320,
        status: "pending",
        createdAt: "2024-11-30T19:45:00Z",
      },
    ],
    subtotal: 2520,
    discounts: [
      { id: "disc_001", name: "Loyalty Discount", type: "percentage", value: 10, appliedAmount: 252, appliedBy: "staff_002" },
    ],
    totalDiscount: 252,
    taxRate: 17,
    taxAmount: 381,
    serviceChargeRate: 5,
    serviceChargeAmount: 113,
    deliveryFee: 0,
    total: 2762,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 2762,
    staffId: "staff_006",
    createdAt: "2024-11-30T19:45:00Z",
    updatedAt: "2024-11-30T19:50:00Z",
  },
  {
    id: "ord_004",
    orderNumber: "ORD-0037",
    restaurantId: "rest_001",
    branchId: "branch_001",
    orderType: "delivery",
    status: "confirmed",
    customerPhone: "+92 304 4567890",
    items: [
      {
        id: "oi_009",
        orderId: "ord_004",
        menuItemId: "item_007",
        menuItemName: "Mutton Biryani",
        categoryId: "cat_003",
        categoryName: "Biryani & Rice",
        quantity: 2,
        unitPrice: 750,
        selectedVariant: { variantId: "var_007a", variantName: "Single", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 1500,
        status: "pending",
        createdAt: "2024-11-30T14:00:00Z",
      },
      {
        id: "oi_010",
        orderId: "ord_004",
        menuItemId: "item_011",
        menuItemName: "Gulab Jamun",
        categoryId: "cat_006",
        categoryName: "Desserts",
        quantity: 1,
        unitPrice: 320,
        selectedVariant: { variantId: "var_011b", variantName: "4 pieces", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 320,
        status: "pending",
        createdAt: "2024-11-30T14:00:00Z",
      },
    ],
    subtotal: 1820,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 309,
    serviceChargeRate: 0,
    serviceChargeAmount: 0,
    deliveryFee: 150,
    total: 2279,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 2279,
    deliveryAddress: "Bungalow 7, DHA Phase 6, Karachi",
    estimatedDeliveryMinutes: 40,
    staffId: "staff_003",
    createdAt: "2024-11-30T14:00:00Z",
    updatedAt: "2024-11-30T14:55:00Z",
  },
];