import type { Order } from "@/types";

export const mockOrders: Order[] = [
  {
    id: "ord_001",
    orderNumber: "ORD-0041",
    restaurantId: "rest_001",
    branchId: "branch_001",
    tableId: "tbl_001",
    tableNumber: "T1",
    orderType: "dine_in",
    status: "confirmed",
    items: [
      {
        id: "oi_001",
        orderId: "ord_001",
        menuItemId: "item_001",
        menuItemName: "Chicken Tikka",
        categoryId: "cat_001",
        categoryName: "BBQ & Grill",
        quantity: 1,
        unitPrice: 750,
        selectedVariant: { variantId: "var_001a", variantName: "Half (6 pcs)", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 750,
        status: "pending",
        createdAt: "2024-11-30T19:15:00Z",
      },
      {
        id: "oi_002",
        orderId: "ord_001",
        menuItemId: "item_004",
        menuItemName: "Chicken Karahi",
        categoryId: "cat_002",
        categoryName: "Karahi & Handi",
        quantity: 1,
        unitPrice: 1200,
        selectedVariant: { variantId: "var_004a", variantName: "Half kg", priceAdjustment: 0 },
        selectedModifiers: [{ groupId: "mod_004", groupName: "Oil Preference", optionId: "opt_004c", optionName: "Desi Ghee", priceAdjustment: 200 }],
        itemTotal: 1400,
        status: "pending",
        createdAt: "2024-11-30T19:15:00Z",
      },
      {
        id: "oi_003",
        orderId: "ord_001",
        menuItemId: "item_009",
        menuItemName: "Tandoori Naan",
        categoryId: "cat_005",
        categoryName: "Breads",
        quantity: 3,
        unitPrice: 60,
        selectedModifiers: [],
        itemTotal: 180,
        status: "pending",
        createdAt: "2024-11-30T19:15:00Z",
      },
      {
        id: "oi_004",
        orderId: "ord_001",
        menuItemId: "item_013",
        menuItemName: "Mango Lassi",
        categoryId: "cat_007",
        categoryName: "Drinks",
        quantity: 2,
        unitPrice: 250,
        selectedVariant: { variantId: "var_013a", variantName: "Regular", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 500,
        status: "pending",
        createdAt: "2024-11-30T19:15:00Z",
      },
    ],
    subtotal: 2830,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 481,
    serviceChargeRate: 5,
    serviceChargeAmount: 142,
    deliveryFee: 0,
    total: 3453,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 3453,
    staffId: "staff_004",
    createdAt: "2024-11-30T19:15:00Z",
    updatedAt: "2024-11-30T19:22:00Z",
  },
  {
    id: "ord_002",
    orderNumber: "ORD-0040",
    restaurantId: "rest_001",
    branchId: "branch_001",
    tableId: "tbl_003",
    tableNumber: "T3",
    orderType: "dine_in",
    status: "confirmed",
    items: [
      {
        id: "oi_005",
        orderId: "ord_002",
        menuItemId: "item_006",
        menuItemName: "Chicken Biryani",
        categoryId: "cat_003",
        categoryName: "Biryani & Rice",
        quantity: 4,
        unitPrice: 550,
        selectedVariant: { variantId: "var_006a", variantName: "Single", priceAdjustment: 0 },
        selectedModifiers: [{ groupId: "mod_006", groupName: "Extras", optionId: "opt_006a", optionName: "Raita", priceAdjustment: 80 }],
        itemTotal: 2520,
        status: "pending",
        createdAt: "2024-11-30T18:00:00Z",
      },
      {
        id: "oi_006",
        orderId: "ord_002",
        menuItemId: "item_002",
        menuItemName: "Seekh Kabab",
        categoryId: "cat_001",
        categoryName: "BBQ & Grill",
        quantity: 1,
        unitPrice: 850,
        selectedVariant: { variantId: "var_002a", variantName: "4 pieces", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 850,
        status: "pending",
        createdAt: "2024-11-30T18:00:00Z",
      },
    ],
    subtotal: 3370,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 573,
    serviceChargeRate: 5,
    serviceChargeAmount: 169,
    deliveryFee: 0,
    total: 4112,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 4112,
    staffId: "staff_004",
    createdAt: "2024-11-30T18:00:00Z",
    updatedAt: "2024-11-30T19:00:00Z",
  },
  {
    id: "ord_003",
    orderNumber: "ORD-0039",
    restaurantId: "rest_001",
    branchId: "branch_001",
    tableId: "tbl_007",
    tableNumber: "T7",
    orderType: "dine_in",
    status: "confirmed",
    items: [
      {
        id: "oi_007",
        orderId: "ord_003",
        menuItemId: "item_005",
        menuItemName: "Mutton Karahi",
        categoryId: "cat_002",
        categoryName: "Karahi & Handi",
        quantity: 1,
        unitPrice: 2200,
        selectedVariant: { variantId: "var_005a", variantName: "Half kg", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 2200,
        status: "pending",
        createdAt: "2024-11-30T19:45:00Z",
      },
      {
        id: "oi_008",
        orderId: "ord_003",
        menuItemId: "item_010",
        menuItemName: "Butter Naan",
        categoryId: "cat_005",
        categoryName: "Breads",
        quantity: 4,
        unitPrice: 80,
        selectedModifiers: [],
        itemTotal: 320,
        status: "pending",
        createdAt: "2024-11-30T19:45:00Z",
      },
    ],
    subtotal: 2520,
    discounts: [
      { id: "disc_001", name: "Loyalty Discount", type: "percentage", value: 10, appliedAmount: 252, appliedBy: "staff_002" },
    ],
    totalDiscount: 252,
    taxRate: 17,
    taxAmount: 381,
    serviceChargeRate: 5,
    serviceChargeAmount: 113,
    deliveryFee: 0,
    total: 2762,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 2762,
    staffId: "staff_006",
    createdAt: "2024-11-30T19:45:00Z",
    updatedAt: "2024-11-30T19:50:00Z",
  },
  {
    id: "ord_004",
    orderNumber: "ORD-0037",
    restaurantId: "rest_001",
    branchId: "branch_001",
    orderType: "delivery",
    status: "confirmed",
    customerPhone: "+92 304 4567890",
    items: [
      {
        id: "oi_009",
        orderId: "ord_004",
        menuItemId: "item_007",
        menuItemName: "Mutton Biryani",
        categoryId: "cat_003",
        categoryName: "Biryani & Rice",
        quantity: 2,
        unitPrice: 750,
        selectedVariant: { variantId: "var_007a", variantName: "Single", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 1500,
        status: "pending",
        createdAt: "2024-11-30T14:00:00Z",
      },
      {
        id: "oi_010",
        orderId: "ord_004",
        menuItemId: "item_011",
        menuItemName: "Gulab Jamun",
        categoryId: "cat_006",
        categoryName: "Desserts",
        quantity: 1,
        unitPrice: 320,
        selectedVariant: { variantId: "var_011b", variantName: "4 pieces", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 320,
        status: "pending",
        createdAt: "2024-11-30T14:00:00Z",
      },
    ],
    subtotal: 1820,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 309,
    serviceChargeRate: 0,
    serviceChargeAmount: 0,
    deliveryFee: 150,
    total: 2279,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 2279,
    deliveryAddress: "Bungalow 7, DHA Phase 6, Karachi",
    estimatedDeliveryMinutes: 40,
    staffId: "staff_003",
    createdAt: "2024-11-30T14:00:00Z",
    updatedAt: "2024-11-30T14:55:00Z",
  },
  {
    id: "ord_005",
    orderNumber: "ORD-0042",
    restaurantId: "rest_001",
    branchId: "branch_001",
    orderType: "takeaway",
    status: "pending",
    customerName: "Hamza Siddiqui",
    customerPhone: "+92 311 2345678",
    items: [
      {
        id: "oi_011",
        orderId: "ord_005",
        menuItemId: "item_006",
        menuItemName: "Chicken Biryani",
        categoryId: "cat_003",
        categoryName: "Biryani & Rice",
        quantity: 2,
        unitPrice: 550,
        selectedVariant: { variantId: "var_006a", variantName: "Single", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 1100,
        status: "pending",
        createdAt: "2024-11-30T20:10:00Z",
      },
      {
        id: "oi_012",
        orderId: "ord_005",
        menuItemId: "item_009",
        menuItemName: "Tandoori Naan",
        categoryId: "cat_005",
        categoryName: "Breads",
        quantity: 2,
        unitPrice: 60,
        selectedModifiers: [],
        itemTotal: 120,
        status: "pending",
        createdAt: "2024-11-30T20:10:00Z",
      },
    ],
    subtotal: 1220,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 207,
    serviceChargeRate: 0,
    serviceChargeAmount: 0,
    deliveryFee: 0,
    total: 1427,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 1427,
    staffId: "staff_002",
    createdAt: "2024-11-30T20:10:00Z",
    updatedAt: "2024-11-30T20:10:00Z",
  },
  {
    id: "ord_006",
    orderNumber: "ORD-0043",
    restaurantId: "rest_001",
    branchId: "branch_001",
    tableId: "tbl_005",
    tableNumber: "T5",
    orderType: "dine_in",
    status: "pending",
    customerName: "Ayesha Malik",
    items: [
      {
        id: "oi_013",
        orderId: "ord_006",
        menuItemId: "item_001",
        menuItemName: "Chicken Tikka",
        categoryId: "cat_001",
        categoryName: "BBQ & Grill",
        quantity: 2,
        unitPrice: 750,
        selectedVariant: { variantId: "var_001b", variantName: "Full (12 pcs)", priceAdjustment: 350 },
        selectedModifiers: [],
        itemTotal: 2200,
        status: "pending",
        createdAt: "2024-11-30T20:25:00Z",
      },
      {
        id: "oi_014",
        orderId: "ord_006",
        menuItemId: "item_013",
        menuItemName: "Mango Lassi",
        categoryId: "cat_007",
        categoryName: "Drinks",
        quantity: 3,
        unitPrice: 250,
        selectedVariant: { variantId: "var_013a", variantName: "Regular", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 750,
        status: "pending",
        createdAt: "2024-11-30T20:25:00Z",
      },
    ],
    subtotal: 2950,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 502,
    serviceChargeRate: 5,
    serviceChargeAmount: 148,
    deliveryFee: 0,
    total: 3600,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 3600,
    staffId: "staff_001",
    createdAt: "2024-11-30T20:25:00Z",
    updatedAt: "2024-11-30T20:25:00Z",
  },
  {
    id: "ord_007",
    orderNumber: "ORD-0044",
    restaurantId: "rest_001",
    branchId: "branch_001",
    orderType: "delivery",
    status: "pending",
    customerName: "Usman Tariq",
    customerPhone: "+92 333 9876543",
    items: [
      {
        id: "oi_015",
        orderId: "ord_007",
        menuItemId: "item_004",
        menuItemName: "Chicken Karahi",
        categoryId: "cat_002",
        categoryName: "Karahi & Handi",
        quantity: 1,
        unitPrice: 1200,
        selectedVariant: { variantId: "var_004b", variantName: "Full kg", priceAdjustment: 600 },
        selectedModifiers: [],
        itemTotal: 1800,
        status: "pending",
        createdAt: "2024-11-30T20:35:00Z",
      },
      {
        id: "oi_016",
        orderId: "ord_007",
        menuItemId: "item_010",
        menuItemName: "Butter Naan",
        categoryId: "cat_005",
        categoryName: "Breads",
        quantity: 4,
        unitPrice: 80,
        selectedModifiers: [],
        itemTotal: 320,
        status: "pending",
        createdAt: "2024-11-30T20:35:00Z",
      },
      {
        id: "oi_017",
        orderId: "ord_007",
        menuItemId: "item_011",
        menuItemName: "Gulab Jamun",
        categoryId: "cat_006",
        categoryName: "Desserts",
        quantity: 1,
        unitPrice: 320,
        selectedVariant: { variantId: "var_011a", variantName: "2 pieces", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 320,
        status: "pending",
        createdAt: "2024-11-30T20:35:00Z",
      },
    ],
    subtotal: 2440,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 415,
    serviceChargeRate: 0,
    serviceChargeAmount: 0,
    deliveryFee: 150,
    total: 3005,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 3005,
    deliveryAddress: "House 12, Block C, North Nazimabad, Karachi",
    estimatedDeliveryMinutes: 45,
    staffId: "staff_003",
    createdAt: "2024-11-30T20:35:00Z",
    updatedAt: "2024-11-30T20:35:00Z",
  },
  {
    id: "ord_008",
    orderNumber: "ORD-0035",
    restaurantId: "rest_001",
    branchId: "branch_001",
    orderType: "takeaway",
    status: "completed",
    customerName: "Bilal Chaudhry",
    customerPhone: "+92 321 1122334",
    items: [
      {
        id: "oi_018",
        orderId: "ord_008",
        menuItemId: "item_007",
        menuItemName: "Mutton Biryani",
        categoryId: "cat_003",
        categoryName: "Biryani & Rice",
        quantity: 3,
        unitPrice: 750,
        selectedVariant: { variantId: "var_007a", variantName: "Single", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 2250,
        status: "pending",
        createdAt: "2024-11-30T16:00:00Z",
      },
    ],
    subtotal: 2250,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 383,
    serviceChargeRate: 0,
    serviceChargeAmount: 0,
    deliveryFee: 0,
    total: 2633,
    paymentStatus: "paid",
    payments: [
      {
        id: "pay_001",
        orderId: "ord_008",
        method: "cash",
        amount: 2633,
        processedAt: "2024-11-30T17:10:00Z",
        processedBy: "staff_002",
      },
    ],
    totalPaid: 2633,
    balance: 0,
    staffId: "staff_002",
    createdAt: "2024-11-30T16:00:00Z",
    updatedAt: "2024-11-30T17:10:00Z",
    completedAt: "2024-11-30T17:10:00Z",
  },
  {
    id: "ord_009",
    orderNumber: "ORD-0034",
    restaurantId: "rest_001",
    branchId: "branch_001",
    tableId: "tbl_002",
    tableNumber: "T2",
    orderType: "dine_in",
    status: "completed",
    customerName: "Sara Ahmed",
    items: [
      {
        id: "oi_019",
        orderId: "ord_009",
        menuItemId: "item_005",
        menuItemName: "Mutton Karahi",
        categoryId: "cat_002",
        categoryName: "Karahi & Handi",
        quantity: 1,
        unitPrice: 2200,
        selectedVariant: { variantId: "var_005b", variantName: "Full kg", priceAdjustment: 800 },
        selectedModifiers: [],
        itemTotal: 3000,
        status: "pending",
        createdAt: "2024-11-30T15:00:00Z",
      },
      {
        id: "oi_020",
        orderId: "ord_009",
        menuItemId: "item_009",
        menuItemName: "Tandoori Naan",
        categoryId: "cat_005",
        categoryName: "Breads",
        quantity: 6,
        unitPrice: 60,
        selectedModifiers: [],
        itemTotal: 360,
        status: "pending",
        createdAt: "2024-11-30T15:00:00Z",
      },
      {
        id: "oi_021",
        orderId: "ord_009",
        menuItemId: "item_013",
        menuItemName: "Mango Lassi",
        categoryId: "cat_007",
        categoryName: "Drinks",
        quantity: 2,
        unitPrice: 250,
        selectedVariant: { variantId: "var_013a", variantName: "Regular", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 500,
        status: "pending",
        createdAt: "2024-11-30T15:00:00Z",
      },
    ],
    subtotal: 3860,
    discounts: [
      { id: "disc_002", name: "Weekend Special", type: "percentage", value: 5, appliedAmount: 193, appliedBy: "staff_001" },
    ],
    totalDiscount: 193,
    taxRate: 17,
    taxAmount: 622,
    serviceChargeRate: 5,
    serviceChargeAmount: 183,
    deliveryFee: 0,
    total: 4472,
    paymentStatus: "paid",
    payments: [
      {
        id: "pay_002",
        orderId: "ord_009",
        method: "cash",
        amount: 4472,
        processedAt: "2024-11-30T16:45:00Z",
        processedBy: "staff_004",
      },
    ],
    totalPaid: 4472,
    balance: 0,
    staffId: "staff_004",
    createdAt: "2024-11-30T15:00:00Z",
    updatedAt: "2024-11-30T16:45:00Z",
    completedAt: "2024-11-30T16:45:00Z",
  },
  {
    id: "ord_010",
    orderNumber: "ORD-0033",
    restaurantId: "rest_001",
    branchId: "branch_001",
    orderType: "delivery",
    status: "completed",
    customerName: "Zara Khan",
    customerPhone: "+92 300 5566778",
    items: [
      {
        id: "oi_022",
        orderId: "ord_010",
        menuItemId: "item_006",
        menuItemName: "Chicken Biryani",
        categoryId: "cat_003",
        categoryName: "Biryani & Rice",
        quantity: 2,
        unitPrice: 550,
        selectedVariant: { variantId: "var_006a", variantName: "Single", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 1100,
        status: "pending",
        createdAt: "2024-11-30T13:00:00Z",
      },
      {
        id: "oi_023",
        orderId: "ord_010",
        menuItemId: "item_011",
        menuItemName: "Gulab Jamun",
        categoryId: "cat_006",
        categoryName: "Desserts",
        quantity: 2,
        unitPrice: 320,
        selectedVariant: { variantId: "var_011b", variantName: "4 pieces", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 640,
        status: "pending",
        createdAt: "2024-11-30T13:00:00Z",
      },
    ],
    subtotal: 1740,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 296,
    serviceChargeRate: 0,
    serviceChargeAmount: 0,
    deliveryFee: 150,
    total: 2186,
    paymentStatus: "paid",
    payments: [
      {
        id: "pay_003",
        orderId: "ord_010",
        method: "cash",
        amount: 2186,
        processedAt: "2024-11-30T14:10:00Z",
        processedBy: "staff_003",
      },
    ],
    totalPaid: 2186,
    balance: 0,
    deliveryAddress: "Flat 3B, Gulshan-e-Iqbal Block 13D, Karachi",
    estimatedDeliveryMinutes: 35,
    staffId: "staff_003",
    createdAt: "2024-11-30T13:00:00Z",
    updatedAt: "2024-11-30T14:10:00Z",
    completedAt: "2024-11-30T14:10:00Z",
  },
  {
    id: "ord_011",
    orderNumber: "ORD-0031",
    restaurantId: "rest_001",
    branchId: "branch_001",
    tableId: "tbl_004",
    tableNumber: "T4",
    orderType: "dine_in",
    status: "cancelled",
    customerName: "Faisal Raza",
    items: [
      {
        id: "oi_024",
        orderId: "ord_011",
        menuItemId: "item_002",
        menuItemName: "Seekh Kabab",
        categoryId: "cat_001",
        categoryName: "BBQ & Grill",
        quantity: 2,
        unitPrice: 850,
        selectedVariant: { variantId: "var_002a", variantName: "4 pieces", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 1700,
        status: "cancelled",
        createdAt: "2024-11-30T12:00:00Z",
      },
    ],
    subtotal: 1700,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 289,
    serviceChargeRate: 5,
    serviceChargeAmount: 85,
    deliveryFee: 0,
    total: 2074,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 2074,
    staffId: "staff_001",
    createdAt: "2024-11-30T12:00:00Z",
    updatedAt: "2024-11-30T12:15:00Z",
  },
  {
    id: "ord_012",
    orderNumber: "ORD-0029",
    restaurantId: "rest_001",
    branchId: "branch_001",
    orderType: "delivery",
    status: "cancelled",
    customerName: "Nadia Hussain",
    customerPhone: "+92 345 6677889",
    items: [
      {
        id: "oi_025",
        orderId: "ord_012",
        menuItemId: "item_007",
        menuItemName: "Mutton Biryani",
        categoryId: "cat_003",
        categoryName: "Biryani & Rice",
        quantity: 1,
        unitPrice: 750,
        selectedVariant: { variantId: "var_007a", variantName: "Single", priceAdjustment: 0 },
        selectedModifiers: [],
        itemTotal: 750,
        status: "cancelled",
        createdAt: "2024-11-30T11:00:00Z",
      },
    ],
    subtotal: 750,
    discounts: [],
    totalDiscount: 0,
    taxRate: 17,
    taxAmount: 128,
    serviceChargeRate: 0,
    serviceChargeAmount: 0,
    deliveryFee: 150,
    total: 1028,
    paymentStatus: "unpaid",
    payments: [],
    totalPaid: 0,
    balance: 1028,
    deliveryAddress: "Plot 22, Sector 11, North Karachi",
    estimatedDeliveryMinutes: 50,
    staffId: "staff_003",
    createdAt: "2024-11-30T11:00:00Z",
    updatedAt: "2024-11-30T11:20:00Z",
  },
];